#!/usr/bin/env perl
use Mojolicious::Lite;
use DBI;
my $user = "ideaMac";
my $pass = "deusXmach";

my $dbh = DBI->connect("DBI:mysql:Idea", $user, $pass);

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

get '/idea' => sub {
	my $self = shift;
	my $idea = $self->param('title');
	my $desc = $self-> param('description');
	my $submitter = $self->param('user');
	my $id = insert_idea($idea, $desc, $submitter);
	$self->render(text => "$id inserted");
};

sub insert_idea
{
	my $title = shift;
	my $description = shift;
	my $user = shift;
	my $q = "INSERT INTO ideas (title, description, user) values (?,?,?)";
	my $sth = $dbh->prepare($q);
	$sth->execute($title, $description, $user);
	return $dbh->{'mysql_insertid'};
}

app->start;
