#!/usr/bin/env perl
use Mojolicious::Lite;
use DBI;
my $user = "lab";
my $pass = "goMOJO";

# CREATE database Idea;
# CREATE TABLE ideas
#(
#	id int auto_increment,
#	primary key(id),
#	title varchar(250),
#	description text,
#	user varchar(250),
#); 

my $dbh = DBI->connect("DBI:mysql:Idea", $user, $pass);
helper db => sub { $dbh };

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

get '/idea' => sub {
	my $self = shift;
	my $idea = $self->param('title');
	my $desc = $self-> param('description');
	my $submitter = $self->param('user');
	$self->render(text =>  "$idea $desc $submitter");
};

app->start;
